/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.basiqueevangelist.enhancedreflection;

import me.basiqueevangelist.enhancedreflection.api.ClassType;
import me.basiqueevangelist.enhancedreflection.api.EClass;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SimpleClassTest {
    @Test void canGetClass() {
        EClass<String> klass = EClass.fromJava(String.class);

        assertEquals(ClassType.CLASS, klass.type());
        assertTrue(klass.isPublic());
        assertTrue(klass.isFinal());
        assertEquals("java.lang.String", klass.name());
        assertEquals("java.lang.Object", klass.superclass().name());
        assertEquals(String.class, klass.raw());
    }
}
